language: cpp
dist: trusty

sudo: required

before_script:
# get yadoms sources
  - git clone --depth=1 -b ${BUILD_BRANCH} git://github.com/Yadoms/yadoms.git 

  - yadomsVersion=$(grep -oP '###[[:space:]]\K.*' yadoms/sources/server/changelog.md -m 1)

# get last yadoms linux binaries
  - wget --no-verbose -U 'Yadoms/1.0.0' http://yadoms.com/builds/linux/Yadoms-$yadomsVersion-Linux.tar.gz
  - tar xzf Yadoms-$yadomsVersion-Linux.tar.gz
  - move Yadoms-$yadomsVersion-Linux\bin yadoms/builds/DEBUG
  
# install python 2.7
  - apt-get install python-setuptools python-dev
  - python -m pip install selenium psutil pyvirtualdisplay unittest-xml-reporting requests

script:
# run tests
  - cd yadoms/tests/user
  - python suite-html.py --headless
