language: cpp
dist: xenial

sudo: required

services:
  - docker
  
before_install:
  - docker pull yadoms/user_tests
  
script:
  - docker run -e YADOMS_BUILD_BRANCH=${TRAVIS_BRANCH} yadoms/user_tests
