language: cpp
dist: trusty

sudo: required

addons:
  chrome: stable
  
before_script:
# get yadoms sources
  - git clone --depth=1 -b ${BUILD_BRANCH} git://github.com/Yadoms/yadoms.git 

  - yadomsVersion=$(grep -oP '###[[:space:]]\K.*' yadoms/sources/server/changelog.md -m 1)

# get last yadoms linux binaries
  - wget --no-verbose -U 'Yadoms/1.0.0' http://yadoms.com/builds/linux/Yadoms-$yadomsVersion-Linux.tar.gz
  - tar xzf Yadoms-$yadomsVersion-Linux.tar.gz
  - mv Yadoms-$yadomsVersion-Linux/bin yadoms/builds/DEBUG
  
# install python 2.7
  - sudo apt-get install python-setuptools python-dev
  - sudo pip install --upgrade pip
  - sudo python -m pip install selenium psutil pyvirtualdisplay unittest-xml-reporting requests

# chrome driver
  #- bundle exec rails runner "Webdrivers::Chromedriver.update"
  - which python
  - wget http://chromedriver.storage.googleapis.com/74.0.3729.6/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d `which python`
  - export CHROME_BIN=chromium-browser
  
script:
# run tests
  - cd yadoms/tests/user
  - python suite-html.py --headless
